"""init tables

Revision ID: 1c6db23b8b6f
Revises: 
Create Date: 2026-05-12 20:09:33.690621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1c6db23b8b6f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commercial_areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('area_cd', sa.String(length=20), nullable=False),
    sa.Column('area_nm', sa.String(length=100), nullable=False),
    sa.Column('gu_nm', sa.String(length=50), nullable=False),
    sa.Column('area_type', sa.String(length=20), nullable=False),
    sa.Column('geom_lat', sa.Float(), nullable=True),
    sa.Column('geom_lng', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commercial_areas_area_cd'), 'commercial_areas', ['area_cd'], unique=True)
    op.create_index(op.f('ix_commercial_areas_gu_nm'), 'commercial_areas', ['gu_nm'], unique=False)
    op.create_table('policy_programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_nm', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('budget_min', sa.BigInteger(), nullable=True),
    sa.Column('budget_max', sa.BigInteger(), nullable=True),
    sa.Column('apply_start', sa.Date(), nullable=True),
    sa.Column('apply_end', sa.Date(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_programs_category'), 'policy_programs', ['category'], unique=False)
    op.create_table('population_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('area_cd', sa.String(length=20), nullable=False),
    sa.Column('year_quarter', sa.String(length=7), nullable=False),
    sa.Column('total_population', sa.Integer(), nullable=True),
    sa.Column('age_10s', sa.Integer(), nullable=True),
    sa.Column('age_20s', sa.Integer(), nullable=True),
    sa.Column('age_30s', sa.Integer(), nullable=True),
    sa.Column('age_40s', sa.Integer(), nullable=True),
    sa.Column('age_50s', sa.Integer(), nullable=True),
    sa.Column('age_60s', sa.Integer(), nullable=True),
    sa.Column('male_ratio', sa.Float(), nullable=True),
    sa.Column('female_ratio', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_cd'], ['commercial_areas.area_cd'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_population_data_area_cd'), 'population_data', ['area_cd'], unique=False)
    op.create_index(op.f('ix_population_data_year_quarter'), 'population_data', ['year_quarter'], unique=False)
    op.create_table('sales_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('area_cd', sa.String(length=20), nullable=False),
    sa.Column('industry_cd', sa.String(length=20), nullable=False),
    sa.Column('industry_nm', sa.String(length=100), nullable=False),
    sa.Column('year_quarter', sa.String(length=7), nullable=False),
    sa.Column('monthly_sales_avg', sa.BigInteger(), nullable=True),
    sa.Column('daily_sales_avg', sa.BigInteger(), nullable=True),
    sa.Column('weekday_sales', sa.BigInteger(), nullable=True),
    sa.Column('weekend_sales', sa.BigInteger(), nullable=True),
    sa.Column('time_slot_sales', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_cd'], ['commercial_areas.area_cd'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_data_area_cd'), 'sales_data', ['area_cd'], unique=False)
    op.create_index(op.f('ix_sales_data_industry_cd'), 'sales_data', ['industry_cd'], unique=False)
    op.create_index(op.f('ix_sales_data_year_quarter'), 'sales_data', ['year_quarter'], unique=False)
    op.create_table('store_counts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('area_cd', sa.String(length=20), nullable=False),
    sa.Column('year_quarter', sa.String(length=7), nullable=False),
    sa.Column('industry_cd', sa.String(length=20), nullable=False),
    sa.Column('store_count', sa.Integer(), nullable=True),
    sa.Column('open_rate', sa.Float(), nullable=True),
    sa.Column('close_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_cd'], ['commercial_areas.area_cd'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_counts_area_cd'), 'store_counts', ['area_cd'], unique=False)
    op.create_index(op.f('ix_store_counts_year_quarter'), 'store_counts', ['year_quarter'], unique=False)
    op.create_table('worker_population',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('area_cd', sa.String(length=20), nullable=False),
    sa.Column('year_quarter', sa.String(length=7), nullable=False),
    sa.Column('total_workers', sa.Integer(), nullable=True),
    sa.Column('age_20s', sa.Integer(), nullable=True),
    sa.Column('age_30s', sa.Integer(), nullable=True),
    sa.Column('age_40s', sa.Integer(), nullable=True),
    sa.Column('age_50s', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_cd'], ['commercial_areas.area_cd'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_population_area_cd'), 'worker_population', ['area_cd'], unique=False)
    op.create_index(op.f('ix_worker_population_year_quarter'), 'worker_population', ['year_quarter'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_population_year_quarter'), table_name='worker_population')
    op.drop_index(op.f('ix_worker_population_area_cd'), table_name='worker_population')
    op.drop_table('worker_population')
    op.drop_index(op.f('ix_store_counts_year_quarter'), table_name='store_counts')
    op.drop_index(op.f('ix_store_counts_area_cd'), table_name='store_counts')
    op.drop_table('store_counts')
    op.drop_index(op.f('ix_sales_data_year_quarter'), table_name='sales_data')
    op.drop_index(op.f('ix_sales_data_industry_cd'), table_name='sales_data')
    op.drop_index(op.f('ix_sales_data_area_cd'), table_name='sales_data')
    op.drop_table('sales_data')
    op.drop_index(op.f('ix_population_data_year_quarter'), table_name='population_data')
    op.drop_index(op.f('ix_population_data_area_cd'), table_name='population_data')
    op.drop_table('population_data')
    op.drop_index(op.f('ix_policy_programs_category'), table_name='policy_programs')
    op.drop_table('policy_programs')
    op.drop_index(op.f('ix_commercial_areas_gu_nm'), table_name='commercial_areas')
    op.drop_index(op.f('ix_commercial_areas_area_cd'), table_name='commercial_areas')
    op.drop_table('commercial_areas')
    # ### end Alembic commands ###
